Add Player Controller
MossPiglets/Fishy pull request #2
Opened 2022-03-14 12:11 UTC by Katarzyna-Kadziolka

2022-03-14 12:23 UTC, Morasiu requested changes

2022-03-14 12:23 UTC, Morasiu commented on Fishy/Assets/_Scripts/PlayerController.cs
> +    public float speed = 7.0f;
```suggestion
    [SerializeField] private float speed = 7.0f;
```

2022-03-14 12:23 UTC, Morasiu commented on Fishy/Assets/_Scripts/PlayerController.cs
> +    public Rigidbody2D rigidbody2d;
It should just be private

2022-03-15 14:41 UTC, Morasiu approved these changes

2022-03-15 18:24 UTC, Morasiu approved these changes

2022-03-15 18:24 UTC, Zofia-Szybalska approved these changes

2022-03-15 18:24 UTC, merged